// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailerWebApplication.Models;

namespace RetailerWebApplication.Migrations
{
    [DbContext(typeof(RetailerContext))]
    [Migration("20220112030407_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RetailerWebApplication.Models.Retailer", b =>
                {
                    b.Property<int>("RetailerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetailerFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetailerLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetailerShopAddres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RetailerId");

                    b.ToTable("Retailer");
                });
#pragma warning restore 612, 618
        }
    }
}
